#!/usr/bin/env python3
# https://passlib.readthedocs.io/en/stable/lib/passlib.apache.html
from passlib.apache import HtpasswdFile
from pathlib import Path
                                                                                                                                                                                                                             passfile='test.htpasswd'

if Path(passfile).is_file():
    ht = HtpasswdFile(passfile)
    ht.set_password("someuser", "new secret password")
    ht.save()
else:
    ht = HtpasswdFile(passfile, new=True)
    set_password("someuser", "really secret password")
    ht.save()
